name: Build and Release Alpaca Safety Monitor

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match "refs/tags/v(.+)") {
            $version = $matches[1]
            Write-Host "Extracted version: $version"
            echo "VERSION=$version" >> $env:GITHUB_ENV
          } else {
            $version = "0.0.1-dev"
            Write-Host "No tag found, using dev version: $version"
            echo "VERSION=$version" >> $env:GITHUB_ENV
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj

      - name: Build Alpaca Safety Monitor
        run: dotnet build SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj -c Release -p:Version=${{ env.VERSION }}

      - name: Publish Alpaca Safety Monitor
        run: dotnet publish SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj -c Release -o publish --self-contained false -p:Version=${{ env.VERSION }}

      - name: Copy configuration
        shell: pwsh
        run: |
          Copy-Item "SFROofsSafetyMonitor/roofs.json" "publish/" -Force
          Write-Host "Published files:"
          Get-ChildItem "publish" -Recurse

      - name: Setup Inno Setup
        shell: pwsh
        run: |
          $url = "https://jrsoftware.org/download.php/is.exe"
          $output = "innosetup.exe"
          Write-Host "Downloading Inno Setup from $url"
          Invoke-WebRequest -Uri $url -OutFile $output
          Write-Host "Installing Inno Setup silently"
          Start-Process -FilePath $output -ArgumentList "/VERYSILENT" -Wait
          Write-Host "Inno Setup installation completed"

      - name: Build Installer
        shell: pwsh
        run: |
          $isccPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          
          if (-not (Test-Path $isccPath)) {
            Write-Host "ISCC.exe not found at $isccPath"
            Get-ChildItem "C:\Program Files (x86)" -Recurse -Name "ISCC.exe" -ErrorAction SilentlyContinue
            exit 1
          }
          
          Write-Host "Building installer with Inno Setup"
          Write-Host "Using version: ${{ env.VERSION }}"
          
          Push-Location SFROofsSafetyMonitor
          & $isccPath AlpacaInstaller.iss
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Inno Setup failed with exit code $LASTEXITCODE"
            Pop-Location
            exit 1
          }
          Pop-Location

      - name: Upload Setup to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: SFROofsSafetyMonitor/SFROofAlpacaSafetyMonitorSetup.exe