name: Build and Release Installer

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.x'

      - name: Restore dependencies
        run: dotnet restore SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj

      - name: Build
        run: dotnet build SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj --configuration Release

      - name: Publish self-contained
        run: dotnet publish SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj --configuration Release --self-contained -r win-x64 -o publish

      - name: Install WiX Toolset
        run: choco install wix --version=3.11.2

      - name: Build Installer
        run: |
          "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" installer/SFROofsSafetyMonitorInstaller.wxs
          "C:\Program Files (x86)\WiX Toolset v3.11\bin\light.exe" SFROofsSafetyMonitorInstaller.wixobj -o SFROofsSafetyMonitorInstaller.msi

      - name: Upload MSI to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: SFROofsSafetyMonitorInstaller.msi