name: Build and Release Alpaca Safety Monitor

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -match "refs/tags/v(.+)") {
            $version = $matches[1]
            Write-Host "Extracted version: $version"
            echo "VERSION=$version" >> $env:GITHUB_ENV
          } else {
            $version = "0.0.1-dev"
            Write-Host "No tag found, using dev version: $version"
            echo "VERSION=$version" >> $env:GITHUB_ENV
          }

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj

      - name: Build Alpaca Safety Monitor
        run: dotnet build SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj -c Release -p:Version=${{ env.VERSION }}

      - name: Publish Alpaca Safety Monitor
        run: dotnet publish SFROofsSafetyMonitor/SFROofsSafetyMonitor.csproj -c Release -o publish --self-contained false -p:Version=${{ env.VERSION }}

      - name: Copy configuration
        shell: pwsh
        run: |
          Copy-Item "SFROofsSafetyMonitor/roofs.json" "publish/" -Force
          Write-Host "Published files:"
          Get-ChildItem "publish" -Recurse

      - name: Setup Inno Setup
        shell: pwsh
        run: |
          Write-Host "Installing Inno Setup via Chocolatey"
          choco install innosetup -y
          Write-Host "Inno Setup installation completed"
          
          # Verify installation
          $isccPath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          if (Test-Path $isccPath) {
            Write-Host "✅ Inno Setup installed successfully at $isccPath"
          } else {
            Write-Host "❌ Inno Setup not found, checking alternative locations..."
            Get-ChildItem "C:\Program Files*" -Recurse -Name "ISCC.exe" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "Found: $_" }
          }

      - name: Build Installer
        shell: pwsh
        run: |
          # Try multiple possible locations for ISCC.exe
          $isccPaths = @(
            "C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
            "C:\Program Files\Inno Setup 6\ISCC.exe",
            "C:\tools\InnoSetup\ISCC.exe"
          )
          
          $isccPath = $null
          foreach ($path in $isccPaths) {
            if (Test-Path $path) {
              $isccPath = $path
              Write-Host "✅ Found ISCC.exe at: $path"
              break
            }
          }
          
          if (-not $isccPath) {
            Write-Host "❌ ISCC.exe not found in any expected location"
            Write-Host "Searching for ISCC.exe..."
            Get-ChildItem "C:\" -Recurse -Name "ISCC.exe" -ErrorAction SilentlyContinue | ForEach-Object { Write-Host "Found: $_" }
            exit 1
          }
          
          Write-Host "Building installer with Inno Setup"
          Write-Host "Using version: ${{ env.VERSION }}"
          
          Push-Location SFROofsSafetyMonitor
          & $isccPath AlpacaInstaller.iss
          if ($LASTEXITCODE -ne 0) {
            Write-Host "❌ Inno Setup failed with exit code $LASTEXITCODE"
            Pop-Location
            exit 1
          }
          Write-Host "✅ Installer built successfully"
          Pop-Location

      - name: Upload Setup to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: SFROofsSafetyMonitor/SFROofsSafetyMonitorSetup.exe